name: Build and Test

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop, release/* ]

jobs:
  build:
    name: Backend Build and Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Backend
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run Tests
      run: |
        cd build
        make test
